parameters:
    sonata.media.provider.file.class: Ok99\PrivateZoneCore\MediaBundle\Provider\FileProvider
    sonata.media.provider.image.class: Ok99\PrivateZoneCore\MediaBundle\Provider\ImageProvider
    sonata.media.thumbnail.format: Ok99\PrivateZoneCore\MediaBundle\Thumbnail\FormatThumbnail
#    sonata.media.provider.file.class: Ok99\PrivateZoneCore\MediaBundle\Provider\DownloadProvider

services:
    sonata.media.provider.file:
        class: %sonata.media.provider.file.class%
        tags:
            - { name: sonata.media.provider }
        arguments: [sonata.media.provider.file, @sonata.media.filesystem.local, @sonata.media.cdn.server, @sonata.media.generator.default, @sonata.media.thumbnail.format, [], [], @sonata.media.metadata.proxy, @doctrine.orm.entity_manager]
        calls:
            - [ setTemplates, [{helper_thumbnail: SonataMediaBundle:Provider:thumbnail.html.twig, helper_view: SonataMediaBundle:Provider:view_file.html.twig}] ]

    sonata.media.provider.image:
        class: %sonata.media.provider.image.class%
        tags:
            - { name: sonata.media.provider }
        arguments: [sonata.media.provider.image, @sonata.media.filesystem.local, @sonata.media.cdn.server, @sonata.media.generator.default, @sonata.media.thumbnail.format, [], [], @sonata.media.adapter.image.gd]
        calls:
            - [ setTemplates, [{helper_thumbnail: SonataMediaBundle:Provider:thumbnail.html.twig, helper_view: SonataMediaBundle:Provider:view_image.html.twig}] ]

#     ok99.privatezone.media.provider.download:
#         class: %sonata.media.provider.file.class%
#         tags:
#             - { name: sonata.media.provider }
#         arguments: [ok99.privatezone.media.provider.download, @sonata.media.filesystem.local, @sonata.media.cdn.server, @sonata.media.generator.default, @sonata.media.thumbnail.format, @sonata.media.metadata.proxy]
#         calls:
#             - [ setTemplates, [{helper_thumbnail: SonataMediaBundle:Provider:thumbnail.html.twig, helper_view: SonataMediaBundle:Provider:view_file.html.twig}] ]