<?php

namespace Ok99\PrivateZoneCore\MediaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Ok99\PrivateZoneCore\ClassificationBundle\Entity\Category;
use Ok99\PrivateZoneCore\MediaBundle\Entity\Media;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
    /**
     * @param Category $category
     * @return Media[]
     */
    public function getCategoryMedias(Category $category)
    {
        try {
            return $this->createQueryBuilder('m')
                ->where('m.category = :category')
                ->andWhere('m.enabled = :true')
                ->orderBy('m.updatedAt', 'desc')
                ->setParameter('category', $category)
                ->setParameter('true', true)
                ->getQuery()->getResult();
        } catch (NoResultException $e) {
            return [];
        }
    }
}
