<?php

namespace Ok99\PrivateZoneCore\MediaBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
use Ok99\PrivateZoneCore\ClassificationBundle\Entity\Category;
use Ok99\PrivateZoneCore\MediaBundle\Entity\Media;
use Ok99\PrivateZoneCore\UserBundle\Entity\User;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends EntityRepository
{
    /**
     * @param Category $category
     * @param User|null $user
     * @return Media[]
     */
    public function getCategoryMedias(Category $category, $user = null)
    {
        try {
            $medias = $this->createQueryBuilder('m')
                ->where('m.category = :category')
                ->andWhere('m.enabled = :true')
                ->orderBy('m.updatedAt', 'desc')
                ->setParameter('category', $category)
                ->setParameter('true', true)
                ->getQuery()->getResult();
        } catch (NoResultException $e) {
            $medias = [];
        }

        if ($user) {
            $medias = array_filter($medias, function (Media $media) use ($user) {
                return
                    !$media->getAllowedUsers()
                    || in_array($user, $media->getAllowedUsers());
            });
        }

        return $medias;
    }

    /**
     * @param User|null $user
     * @return Media[]
     */
    public function getMedias($user = null)
    {
        try {
            $medias = $this->createQueryBuilder('m')
                ->andWhere('m.enabled = :true')
                ->orderBy('m.updatedAt', 'desc')
                ->setParameter('true', true)
                ->getQuery()->getResult();
        } catch (NoResultException $e) {
            $medias = [];
        }

        if ($user) {
            $medias = array_filter($medias, function (Media $media) use ($user) {
                return
                    !$media->getAllowedUsers()
                    || in_array($user, $media->getAllowedUsers());
            });
        }

        return $medias;
    }
}
